management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.backendguru: DEBUG
